version: '3.8'
services:
  db:
    image: postgres:15
    container_name: upay-postgres
    environment:
      POSTGRES_DB: springbootdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: upay-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/springbootdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_JWT_SECRET: ${APP_JWT_SECRET:-ZmFrZV9kZWNvZGVkX2Jhc2U2NF9zZWNyZXRfa2V5X3RvX2NoYW5nZQ==}
      APP_JWT_EXPIRATION_MS: 3600000
      JAVA_OPTS: -Xms256m -Xmx512m
    ports:
      - "8080:8080"

volumes:
  db_data:
